# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 0
/control/saveHistory
/run/verbose 0
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 2
#
# Initialize kernel
/run/initialize
#

# Primitive scorers
# => Step PDD-3C
#/control/execute mac/scorers.mac

/run/printProgress 10000

# => Step HVL-6A
/run/beamOn 100000
#/run/beamOn 100000
#/run/beamOn 100000
#/run/beamOn 100000
#/run/beamOn 100000

# => Step PDD-3D
#/score/dumpQuantityToFile Mesh2 dose analysis/dose_profile.out
#/score/dumpQuantityToFile Mesh2 protonCellFlux analysis/dose_profile.out